// Code generated by MockGen. DO NOT EDIT.
// Source: debezium/unified_system_parameter_helper.go

// Package debezium is a generated GoMock package.
package debezium

import (
	json "encoding/json"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUSP is a mock of USP interface.
type MockUSP struct {
	ctrl     *gomock.Controller
	recorder *MockUSPMockRecorder
}

// MockUSPMockRecorder is the mock recorder for MockUSP.
type MockUSPMockRecorder struct {
	mock *MockUSP
}

// NewMockUSP creates a new mock instance.
func NewMockUSP(ctrl *gomock.Controller) *MockUSP {
	mock := &MockUSP{ctrl: ctrl}
	mock.recorder = &MockUSPMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUSP) EXPECT() *MockUSPMockRecorder {
	return m.recorder
}

// GetDescription mocks base method.
func (m *MockUSP) GetDescription(variable string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDescription", variable)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDescription indicates an expected call of GetDescription.
func (mr *MockUSPMockRecorder) GetDescription(variable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDescription", reflect.TypeOf((*MockUSP)(nil).GetDescription), variable)
}

// GetValue mocks base method.
func (m *MockUSP) GetValue(variable string) json.RawMessage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValue", variable)
	ret0, _ := ret[0].(json.RawMessage)
	return ret0
}

// GetValue indicates an expected call of GetValue.
func (mr *MockUSPMockRecorder) GetValue(variable interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValue", reflect.TypeOf((*MockUSP)(nil).GetValue), variable)
}

// GetValueAs mocks base method.
func (m *MockUSP) GetValueAs(variable string, out any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueAs", variable, out)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetValueAs indicates an expected call of GetValueAs.
func (mr *MockUSPMockRecorder) GetValueAs(variable, out interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueAs", reflect.TypeOf((*MockUSP)(nil).GetValueAs), variable, out)
}
